### PR TITLE
Address all misspellings found by goreportcard

### LINKED ISSUE #8: Address some misspellings
Xref: https://goreportcard.com/report/github.com/m-lab/ndt7-client-go

### PR DESCRIPTION
**Pull request by bassosimone**
Closes #8

### CODE REVIEW

**Comment by pboothe** [comment]
Fixed the english in the title of the PR ;)

**Comment by bassosimone** [comment]
@pboothe :
> Fixed the english in the title of the PR ;)

:-D

**Comment by bassosimone** [comment]
I've been slow in merging this PR because I think we needed to look into the CI failures that may be related to the similar issues reported to us by @miguelangelnet. Looking into this now.

**Comment by bassosimone** [comment]
So, it seems the problem we're seeing here is caused by me misunderstanding how the staging service of mlab-ns works. It usually returns `mlab4` servers, but not always. I've asked in the M-Lab slack whether this is working as intended or not. But, I suspect we would not be seeing these issues when I will complete the tasks required to have a `ndt7` name in mlab-ns: https://github.com/m-lab/mlab-ns/issues/188. For this reason, I think it's safe to merge this PR even with failing CI, as there is a clear explanation of why the CI is failing. I'd also like to not restart the build and keep it failing for documentational purposes.

**Pull request merged**
